#!/bin/sh

perl -0777 -ne 'BEGIN { $e = 0 } while (/^(?!\s*\/\/|\s*unsafe|\s*pub unsafe)(\N*) fn (\w+)(<\N*>)?(\((?!&\s*self|&\x27\w+\s+self|&mut\s+self|&\x27\w+\s+mut\s+self)[^{;]+)\{(\s+)(?!assert_init|assert_not_init|skip_assert_init)\S/gms) { print "$ARGV: $2$4\n"; $e = 1 }; END { exit $e }' src/*.rs src/auto/*.rs
