// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use ffi;

glib_wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct IconSet(Boxed<ffi::GtkIconSet>);

    match fn {
        copy => |ptr| gobject_ffi::g_boxed_copy(ffi::gtk_icon_set_get_type(), ptr as *mut _) as *mut ffi::GtkIconSet,
        free => |ptr| gobject_ffi::g_boxed_free(ffi::gtk_icon_set_get_type(), ptr as *mut _),
        get_type => || ffi::gtk_icon_set_get_type(),
    }
}
