// This file was generated by gir (df8a3f3) from gir-files (11e0e6d)
// DO NOT EDIT

use glib::translate::*;
use glib::types;
use ffi;

use object::*;
use Bin;
use Buildable;
use Container;
use Widget;

pub type ListBoxRow = Object<ffi::GtkListBoxRow>;

unsafe impl Upcast<Widget> for ListBoxRow { }
unsafe impl Upcast<Container> for ListBoxRow { }
unsafe impl Upcast<Bin> for ListBoxRow { }
unsafe impl Upcast<Buildable> for ListBoxRow { }

impl ListBoxRow {
    #[cfg(gtk_3_10)]
    pub fn new() -> ListBoxRow {
        unsafe {
            Widget::from_glib_none(ffi::gtk_list_box_row_new()).downcast_unchecked()
        }
    }

    #[cfg(gtk_3_10)]
    pub fn changed(&self) {
        unsafe {
            ffi::gtk_list_box_row_changed(self.to_glib_none().0);
        }
    }

    #[cfg(gtk_3_14)]
    pub fn get_activatable(&self) -> bool {
        unsafe {
            from_glib(ffi::gtk_list_box_row_get_activatable(self.to_glib_none().0))
        }
    }

    #[cfg(gtk_3_10)]
    pub fn get_header(&self) -> Option<Widget> {
        unsafe {
            from_glib_none(ffi::gtk_list_box_row_get_header(self.to_glib_none().0))
        }
    }

    #[cfg(gtk_3_10)]
    pub fn get_index(&self) -> i32 {
        unsafe {
            ffi::gtk_list_box_row_get_index(self.to_glib_none().0)
        }
    }

    #[cfg(gtk_3_14)]
    pub fn get_selectable(&self) -> bool {
        unsafe {
            from_glib(ffi::gtk_list_box_row_get_selectable(self.to_glib_none().0))
        }
    }

    #[cfg(gtk_3_14)]
    pub fn is_selected(&self) -> bool {
        unsafe {
            from_glib(ffi::gtk_list_box_row_is_selected(self.to_glib_none().0))
        }
    }

    #[cfg(gtk_3_14)]
    pub fn set_activatable(&self, activatable: bool) {
        unsafe {
            ffi::gtk_list_box_row_set_activatable(self.to_glib_none().0, activatable.to_glib());
        }
    }

    #[cfg(gtk_3_10)]
    pub fn set_header<T: Upcast<Widget>>(&self, header: Option<&T>) {
        unsafe {
            ffi::gtk_list_box_row_set_header(self.to_glib_none().0, header.map(Upcast::upcast).to_glib_none().0);
        }
    }

    #[cfg(gtk_3_14)]
    pub fn set_selectable(&self, selectable: bool) {
        unsafe {
            ffi::gtk_list_box_row_set_selectable(self.to_glib_none().0, selectable.to_glib());
        }
    }

}

impl types::StaticType for ListBoxRow {
    #[inline]
    fn static_type() -> types::Type {
        unsafe { from_glib(ffi::gtk_list_box_row_get_type()) }
    }
}
